[package]
name = "supraCharger"
version = "1.0.0"
authors = []

[addresses]
exampleAddress ="0xf4125b6cf73835e5fb510f4a638ed5e3885a256b5b9bc8ed2e3306468b01720a"

[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/SUPRANolan/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dev-dependencies]
